######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 29 23:10:35 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h radio.h ranges.h
SOURCES += globj.cpp main.cpp mainwindow.cpp radio.cpp
QT += opengl
