######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 30 22:59:21 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h radio.h ranges.h signal.h
SOURCES += globj.cpp main.cpp mainwindow.cpp radio.cpp signal.cpp
QT += opengl
